language: python
python:
 - "2.6"
 - "2.7"
 - "3.1"
 - "3.2"
 - "pypy"
script: python setup.py test 
install: pip install distribute --use-mirrors
notifications:
  email: false
  irc: "irc.freenode.org#pymaging"
